### PR TITLE
store path to the last selected file and open the next dialog from there

### PR DESCRIPTION
**Pull request by pionere**
does this solve #18 ?

### CODE REVIEW

**Comment by AJenbo** [comment]
Thoug it also helps with the same issue as #18 they are two different features. i have added an example to the issue to make it more clear how it should work.


Regarding this PR, could you make the path persistent (by saving it to the config) so that it is remembered after closing the application.

**Comment by pionere** [comment]
I'm not really convinced that it is a good idea to update the config-file whenever a new file is opened. There is already a "Working Directory" setting if someone wants a persistent location.

Hmm, maybe it could be done in on_actionQuit_triggered ? Is that called when the application is closed by other means?

**Comment by AJenbo** [comment]
Others atleast appear to be using it in that way: https://github.com/GTRONICK/QBack/blob/master/bumain.cpp#L868

**Comment by pionere** [comment]
That would still make the Working Directory configuration entry obsolete.
So either we get rid of the Working Directory entry, or make it optional and if it is set is should override the lastFilePath.

**Comment by AJenbo** [comment]
Isn't that serting in regards to exporting?

**Comment by pionere** [comment]
nope.

**Comment by AJenbo** [comment]
Ok that isn't really informative...

**Comment by pionere** [comment]
> Ok that isn't really informative...

? What information do you need? It has nothing to do with exporting. Only used on mainwindow.cpp as the base directory to OpenFile.

**Comment by AJenbo** [comment]
Thanks. In that case I think this feature clashes with the working directory and I'm not sure how we could mesh them in a good way.

Two solutions I can think of:
- If the workdir is blank (first use) then set it based on the first opened file
- Remove the setting and have it update to where the latest file was opened

**Comment by pionere** [comment]
something like this? I went with the second option:
WorkingDirectory setting is removed.
LastFilePath setting added and stored when the user closes the application (the main window is destroyed).

**Pull request merged**
