### PR TITLE
add 'Open As' option

### PR DESCRIPTION
**Pull request by pionere**
- open cel/cl2 files (and clx, til files in the future?) with additional parameters

Allows to open files affected by #37.

### CODE REVIEW

**Comment by AJenbo** [comment]
clx is not affected by the issue.

**Comment by pionere** [comment]
> clx is not affected by the issue.

yes, just wanted to say that the framework which is built by this PR might be used later for other things. Like loading til/sol/min filesets in a more dynamic way, or pre-applying TRN files, etc...

**Review by AJenbo — APPROVED** [review]

**Comment by pionere** [comment]
@AJenbo : could you please merge this now? It seems to work.

**Comment by AJenbo** [comment]
Yeah just tested it my self :)

**Comment by AJenbo** [comment]
This will probably also be useful when opening other formats like png since we can use it to specify how to cut it in to frames.

**Pull request merged**
