### PR TITLE
start github jobs on any push/pull request

### PR DESCRIPTION
**Pull request by pionere**

### CODE REVIEW

**Comment by AJenbo** [comment]
I don't think I see the need for this?

**Comment by pionere** [comment]
just wanted to reduce the back and forth messages due to clang/CodeFactor errors.
Feel free to close it.

**Comment by AJenbo** [comment]
Hm I'm not sure that would have that result. P.s. hope you saw that 32bit Windows builds are now being done by the CI.

**Comment by AJenbo** [comment]
Was this for helping with testing changes? Maybe another option could be to open them as Drafts while you work on them?

**Comment by pionere** [comment]
Right, this change is no longer necessary.

**Pull request closed without merging**
