### PR TITLE
Correct exporting variable size frames II.

### PR DESCRIPTION
**Pull request by pionere**
#25

### CODE REVIEW

**Review by AJenbo — APPROVED** [review]
<3

**Comment by pionere** [comment]
#25 is supposed to be completed by this, or do you see any other shortcomings?

**Comment by AJenbo** [comment]
Thanks, I expected it to be close automatically, but for that the comment should have been "fixes #25" :)

**Comment by pionere** [comment]
well, maybe next time. But I would not want to close other's PR anyway, so...

**Comment by AJenbo** [comment]
#25 is an issue not a PR :) I normally see validating that it fixes the issue it proports to to be part of the review, but do it which ever way you prefer.

**Pull request merged**
