### PR TITLE
support playback with color cycling

### PR DESCRIPTION
**Pull request by pionere**
cycle

### CODE REVIEW

**Comment by AJenbo** [comment]
Very interesting, maybe we could eventually allow for a way to define and preview custom cycles :)

**Comment by AJenbo** [comment]
Really nice that the pallets are animating too :+1:

**Comment by pionere** [comment]
> Very interesting, maybe we could eventually allow for a way to define and preview custom cycles :)

Hm.. I would wait with that. We will have enough trouble to consider 'protected' palette ranges during the import of png/pcx files...

**Comment by AJenbo** [comment]
Yeah I'm not saying now, it's not like the game e is flexible about it either

**Pull request merged**
